version: '3.5'
services:
  api1:
    # image: thalesmaciel/recoba
    build: .
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_SSLMODE: disable
      PORT: 80
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'
    networks:
      - backend

  api2:
    # image: thalesmaciel/recoba
    build: .
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_SSLMODE: disable
      PORT: 80
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'
    networks:
      - backend

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.2GB'
    networks:
      - backend

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: '2.0GB'
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:7.5.4
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "password"
      GF_USERS_ALLOW_SIGN_UP: "false"
  
volumes:
  grafana_data:
  cockroachdb_data1:
  cockroachdb_data2:

networks:
  backend:
    driver: bridge

